name: GitHub Metrics

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Output
          filename: metrics.svg
          config_timezone: Asia/Karachi
          config_display: large
          config_animations: true
          config_padding: 0, 8 + 11%
          template: terminal@dark

          # Show only current year contributions (activity)
          base: activity

          # Filter contributions to current year only
          config_activity_year: current
